version: 2.1
jobs:
  Production_Build:
    machine:
      image: ubuntu-1604:201903-01
  
    steps:
      - checkout
      - restore_cache:
          keys:
          - node
      - run:
          name: Install node@v12.16.3
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v12.16.3
            nvm use v12.16.3
            nvm alias default v12.16.3

      - run:
          name: Check node version
          command: |
            node -v

      - run:
          name: Docker start
          command: |
            docker-compose up --build
            
      - save_cache:
          paths:
            - node_modules
          key: node
          
orbs:
  jira: circleci/jira@1.3.1
workflows:
  Prod_Build_and_Deploy_on_Approval:
    jobs:
      - Manual_Approval:
          type: approval
          filters:
            branches:
              only: master
      - Production_Build:
          requires:
            - Manual_Approval
          post-steps:
            - jira/notify:
                environment_type: production
                job_type: deployment
          filters:
            branches:
              only: master
              